{{- if .Values.module.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: module-controller-manager
  namespace: {{ .Values.global.namespace }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
