{{- if .Values.server.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: {{ .Values.global.namespace }}
  labels:
    app: server
spec:
  type: {{ .Values.server.service.type }}
  selector:
    app: server
  ports:
  - name: https
    port: {{ .Values.server.service.port }}
    targetPort: {{ .Values.server.service.targetPort }}
    protocol: TCP
{{- end }}
