{{- if .Values.version.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: version-controller-manager
  namespace: {{ .Values.global.namespace }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
