# This rule is not used by the project kerrareg itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the module.defdev.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kerrareg
    app.kubernetes.io/managed-by: kustomize
  name: kerrareg-editor-role
rules:
- apiGroups:
  - module.defdev.io
  resources:
  - kerraregs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - module.defdev.io
  resources:
  - kerraregs/status
  verbs:
  - get
